routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginsController;
use App\Http\Controllers\RegistroController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PeticionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/homeback', [HomeController::class, 'indexBackend'])->name('home.indexBackend');
Route::get('/home', [HomeController::class, 'indexHome'])->name('home.indexHome');


Route::get('/login', [LoginsController::class, 'index'])->name('login.index');
Route::post('/login', [LoginsController::class, 'store'])->name('login.store');

Route::get('/loginbackend', [LoginsController::class, 'indexback'])->name('loginback.indexback');
Route::post('/loginbackend', [LoginsController::class, 'storeback'])->name('loginback.storeback');

Route::get('/registro', [RegistroController::class, 'index'])->name('registro.index');
Route::post('/registro', [RegistroController::class, 'store'])->name('registro.store');

Route::resource('homeback/users', UserController::class)->names('backend.users');



Route::get('/nuevoservicios', [PeticionController::class, 'index'])->name('peticion.index');
        Route::post('/nuevoservicios', [PeticionController::class, 'store'])->name('peticion.store');

Route::get('/servicios', [PeticionController::class, 'indexServicio'])->name('peticionServicio.index');
Route::post('/servicios/ver/{id}', [PeticionController::class, 'show'])->name('producto.show');

app/Http/Livewire/UserIndex.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class UserIndex extends Component
{
    public function render()
    {
        return view('livewire.user-index');
    }
}

app/Http/Livewire/UsersIndex.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;
use Livewire\WithPagination;

class UsersIndex extends Component
{
    use WithPagination;
    public $search;
    protected $paginationTheme='bootstrap';
    public function updatingSearch(){
        $this->resetPage();
    }
    public function render()
    {
        $users= User::where('name','LIKE', '%'. $this->search.'%')
            ->get();
        return view('livewire.users-index', compact('users'));
    }
}

resources/views/livewire/users-index.blade.php
<div>
    <!-- Modal -->
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
        data-whatever="@mdo">Nuevo</button>
    <br>
    <br>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Nuevo Usuario</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('backend.users.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Nombre:</label>
                            <input type="text" class="form-control" id="recipient-name" name="name" required>
                        </div>
                        
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Email:</label>
                            <input type="text" class="form-control" id="recipient-name" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">password:</label>
                            <input type="password" class="form-control" id="recipient-name" name="password" required>
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese el Nombre o Correo de un Usuario">
        </div>
        @if ($users->count())

            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                        
                            
                                <td>{{ $user->email }}</td>
                                <td></td>
                                <td width="10px">
                                    <a class="btn btn-primary"
                                        href="{{ route('backend.users.edit', $user) }}">Editar</a>
                                </td>
                                <td>
                                    <form action="{{ route('backend.users.destroy', $user) }}" method="post">

                                        @csrf
                                        @method('delete')
                                        <input type="hidden" name="id" value="$user">
                                        <input type="hidden" namespace="_method" value="delete">
                                        <button type="submit" class="btn btn-primary btnModalEliminar" data-id="$user">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                <path
                                                    d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
            </div>
        @else
            <div class="card-body">
                <strong>No hay Registros</strong>

            </div>


        @endif
    </div>

</div>