routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginsController;
use App\Http\Controllers\RegistroController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PeticionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/homeback', [HomeController::class, 'indexBackend'])->name('home.indexBackend');
Route::get('/home', [HomeController::class, 'indexHome'])->name('home.indexHome');


Route::get('/login', [LoginsController::class, 'index'])->name('login.index');
Route::post('/login', [LoginsController::class, 'store'])->name('login.store');

Route::get('/loginbackend', [LoginsController::class, 'indexback'])->name('loginback.indexback');
Route::post('/loginbackend', [LoginsController::class, 'storeback'])->name('loginback.storeback');

Route::get('/registro', [RegistroController::class, 'index'])->name('registro.index');
Route::post('/registro', [RegistroController::class, 'store'])->name('registro.store');

Route::resource('homeback/users', UserController::class)->names('backend.users');



Route::get('/nuevoservicios', [PeticionController::class, 'index'])->name('peticion.index');
        Route::post('/nuevoservicios', [PeticionController::class, 'store'])->name('peticion.store');

Route::get('/servicios', [PeticionController::class, 'indexServicio'])->name('peticionServicio.index');
Route::post('/servicios/ver/{id}', [PeticionController::class, 'show'])->name('producto.show');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use App\Role;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend/users/index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        $user=new User();
        $user->name=$request->name;
        $user->email=$request->email;
        $user->password=$request->password;       
        $user->save();
        return view('backend/users/index');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->nombre=$request->nombre;
        $user->apellido=$request->apellido;
        $user->email=$request->email;
        $user->telefono=$request->telefono;      
        $user->save();
        $user->roles()->sync($request->roles);
        return redirect()->to('backend/users/index')->with('info', 'Se asigno El rol Correctamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->to('homeback/users');

    }
}

resources/views/backend/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Asignar un Rol</h1>
@stop

@section('content')
@if (session('info'))
    <div class="alert alert-success">
        <strong>{{session('info')}}</strong>
    </div>
    
@endif
<form action="{{route('backend.users.update',$user )}}" method="POST">
    @csrf
    @method('put')
<div class="card">
    <div class="card-body">
        <p class="h5">Nombre:</p>
        <input class="form-control" name="nombre" value="{{$user->nombre}}">
        <p class="h5">Apellido:</p>
        <input class="form-control" name="apellido" value="{{$user->apellido}}">
        <p class="h5">Email:</p>
        <input class="form-control" name="email" value="{{$user->email}}">
        <p class="h5">Telefono:</p>
        <input class="form-control" name="telefono" value="{{$user->telefono}}">

    </div>
</div>
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/backend/users/index.blade.php
@extends('adminlte::page')
@extends('layout.general')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Lista de Usuarios</h1>
@stop

@section('content')
@if (session('info'))


<div class="alert alert-secondary" role="alert">
{{session('info')}}
</div>
    
@endif
    @livewire('users-index')
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop